WIFIMARKETING/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from api import views

urlpatterns = [
    path("email_verify_code", views.email_verify_code, name="email_verify_code"),
    path("request_send_code", views.request_send_code, name="request_send_code"),
    path(
        "client_request_connect",
        views.client_request_connect,
        name="client_request_connect",
    ),
    path("kick_out_client", views.kick_out_client, name="kick_out_client"),
    path(
        "request_delete_client",
        views.request_delete_client,
        name="request_delete_client",
    ),
    path(
        "request_student_information",
        views.request_student_information,
        name="request_student_information",
    ),
    path(
        "request_list_student_auto_complete",
        views.request_list_student_auto_complete,
        name="request_list_student_auto_complete",
    ),
    path(
        "request_check_student_information",
        views.request_check_student_information,
        name="request_check_student_information",
    ),
]

main/urls.py
from django.urls import path, include
from main import views
from main.views import *

urlpatterns = [
    path("guest/s/default/", views.guest_default_portal, name="guest_default_portal"),
    path(
        "guest/connections",
        views.guest_client_connections,
        name="guest_client_connections",
    ),
    path("guest/list", views.guest_client_list, name="guest_client_list"),
    path(
        "guest/list/<id>",
        views.UpdateUserInformation.as_view(),
        name="UpdateUserInformation",
    ),
    path(
        "student/list", StudentInformationList.as_view(), name="StudentInformationList"
    ),
    path("", views.home, name="home"),
]

main/models.py
from django.db import models


# Create your models here.

class DeviceType(models.Model):
    device_type = models.CharField(max_length=1000)

    def __str__(self):
        return self.device_type


class StudentInformation(models.Model):
    student_id = models.CharField(max_length=100)
    student_code = models.CharField(max_length=100)
    student_name = models.CharField(max_length=200)
    student_classmate = models.CharField(max_length=100)
    student_email = models.CharField(max_length=100)

    def __str__(self):
        return self.student_code


class UserInformation(models.Model):
    email = models.CharField(max_length=1000, verbose_name="Địa chỉ email")
    name = models.CharField(max_length=1000, verbose_name="Họ và tên sinh viên")
    classmate = models.CharField(max_length=100, verbose_name="Khóa học/lớp học")
    phone = models.IntegerField(verbose_name="Số điện thoại đăng ký")
    device_mac_address = models.CharField(
        max_length=20, unique=True, verbose_name="Địa chỉ MAC của thiết bị"
    )
    bw_upload = models.IntegerField(
        default=10000, verbose_name="Băng thông upload (Kbps)"
    )
    bw_download = models.IntegerField(
        default=10000, verbose_name="Băng thông download (Kbps)"
    )
    time_used = models.IntegerField(default=60, verbose_name="Thời gian sử dụng (Phút)")
    ap_mac_address = models.CharField(max_length=20, verbose_name="Địa chỉ MAC của AP")
    device_type = models.ForeignKey(
        "DeviceType", on_delete=models.CASCADE, verbose_name="Loại thiết bị"
    )
    device_model = models.CharField(max_length=1000, verbose_name="Tên thiết bị")
    code = models.IntegerField(null=True)
    status = models.CharField(default="DEACTIVE", max_length=200, verbose_name="Trạng thái")

    def __str__(self):
        return self.email

main/forms.py
from django.forms import ModelForm
from django import forms
from main.models import *
import random

class UserInformationForm(forms.ModelForm):
    class Meta:
        model = UserInformation
        fields = [
            "email",
            "name",
            "classmate",
            "device_mac_address",
            "ap_mac_address",
            "phone",
            "device_type",
            "device_model",
        ]

    def clean_email(self):
        email = self.cleaned_data.get("email")
        count_email = UserInformation.objects.filter(email=email.lower()).count()
        if count_email >= 2:
            raise forms.ValidationError("Vượt quá số thiết bị đăng ký với email này")
        # elif "student.vlute.edu.vn" not in email or 'vlute.edu.vn' not in email:
        elif '@' not in email:
            raise forms.ValidationError("Định dạng email không hợp lệ vui lòng thử lại")
        else:
            return email.lower()

    def clean_device_mac_address(self):
        device_mac_address = self.cleaned_data.get("device_mac_address")
        count_device_mac_address = UserInformation.objects.filter(device_mac_address=device_mac_address).count()
        if count_device_mac_address != 0:
            raise forms.ValidationError("Thiết bị đã được đăng ký, vui lòng thử lại")
        else:
            return device_mac_address

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if len(str(phone)) !=9:
            raise forms.ValidationError("Số điện thoại không hợp lệ, vui lòng thử lại")
        else:
            return phone

STATUS_CHOICE = (
    ('ACTIVE','ACTIVE'),
    ('DEACTIVE','DEACTIVE'),
    ('BLACKLIST','BLACKLIST')
)

class UserInformationFormUpdate(forms.ModelForm):
    status = forms.ChoiceField(choices=STATUS_CHOICE, label='Trạng thái')
    class Meta:
        model = UserInformation
        fields = [
            'device_mac_address',
            'bw_upload',
            'bw_download',
            'time_used',
            'status'
        ]

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from main.forms import *
from main.models import *
from django.core.mail import send_mail
from django.conf import settings
from main.unifi_client import UnifiClient
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from django.views.generic import ListView
from django.utils.decorators import method_decorator
import random
import time


def guest_default_portal(request):
    try:
        if request.method == "GET":
            form = UserInformationForm
            ssid = request.GET.get("ssid")
            client = request.GET.get("id")
            ap = request.GET.get("ap")
            data = {
                "form": form,
                "ssid": ssid.upper(),
                "client": client.lower(),
                "ap": ap.lower(),
            }
            count_client = UserInformation.objects.filter(device_mac_address=client).count()
            if count_client == 0:
                return render(
                    request, template_name="guest_client_register.html", context=data
                )
            else:
                Model = UserInformation.objects.get(device_mac_address=client)
                client_status = Model.status
                if client_status == "DEACTIVE":
                    return render(
                        request, template_name="guest_confirm_code.html", context=data
                    )
                elif client_status == 'BLACKLIST':
                    return render(
                        request, template_name="guest_black_list.html", context=data
                    )
            return render(request, template_name="guest_welcome.html", context=data)
        elif request.method == "POST":
            form_data = UserInformationForm(request.POST)
            client = form_data["device_mac_address"].value()
            ap = form_data["ap_mac_address"].value()
            if form_data.is_valid():
                form_data.save()
                client = form_data.cleaned_data["device_mac_address"]
                Model = UserInformation.objects.get(device_mac_address=client)
                email = Model.email
                code = random.randint(100000, 999999)
                Model.code = code
                Model.save()
                data = {
                    "client": client,
                    "ap": ap,
                }
                send_mail(
                    "Số xác thực đăng ký WiFi VLUTE",
                    "Xin chào người sử dụng\n\n"
                    "Số xác thực đăng ký WiFi VLUTE của bạn là: "
                    + str(code)
                    + "\n\n"
                    + "Nếu cần giúp đỡ, xin vui lòng liên hệ Khoa công nghệ thông tin qua các kênh sau đây: \n\n"
                    + "- Địa chỉ: \n"
                    + "    ◽️ Văn phòng khoa phòng C601\n"
                    + "    ◽️ Trường Đại Học Sư Phạm Kỹ Thuật Vĩnh Long\n"
                    + "- Phone: (+84) 02703828320\n"
                    + "- Email: cit@vlute.edu.vn\n\n"
                    + "TRÂN TRỌNG CÁM ƠN!",
                    settings.EMAIL_HOST_USER,
                    [
                        email,
                    ],
                )
                return render(
                    request, template_name="guest_confirm_code.html", context=data
                )
            else:
                data = {"form": form_data, "client": client, "ap": ap}
                return render(
                    request, template_name="guest_client_register.html", context=data
                )
    except Exception as error:
        return HttpResponse(error)


@login_required
def guest_client_connections(request):
    try:
        if request.method == "GET":
            clients = UnifiClient().get_client_detail_information()
            data = {"clients": clients}
            return render(
                request, template_name="guest_client_connections.html", context=data
            )
    except Exception as error:
        return HttpResponse(error)


@login_required
def guest_client_list(request):
    try:
        if request.method == "GET":
            clients = UserInformation.objects.order_by("email")
            data = {"clients": clients}
            return render(request, template_name="guest_client_list.html", context=data)

    except Exception as error:
        return HttpResponse(error)


@login_required
def home(request):
    try:
        if request.method == "GET":
            return render(request, template_name="home.html")

    except Exception as error:
        return HttpResponse(error)


class UpdateUserInformation(UpdateView):
    model = UserInformation
    form_class = UserInformationFormUpdate
    template_name = "update_user_information.html"
    success_url = "/guest/list"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_object(self, **kwargs):
        return UserInformation.objects.get(id=self.kwargs["id"])

    def form_valid(self, form):
        if form.is_valid():
            client = form["device_mac_address"].value()
            bw_upload = form["bw_upload"].value()
            bw_download = form["bw_download"].value()
            time_used = form["time_used"].value()
            UnifiClient().set_bw_client(client, time_used, bw_upload, bw_download)
        return super().form_valid(form)


class StudentInformationList(ListView):
    model = StudentInformation
    context_object_name = "students"
    template_name = "student_list.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

main/templates/base.html
<!DOCTYPE html>
<html lang="Vi">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="/media/logo.png" />
    <title>{% block title %} {% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'main/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/datatable.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/auto-complete.css' %}">
    <!-- ------>
    <script src="{% static 'main/js/jquery.min.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'main/js/jquery.email-autocomplete.js' %}"></script>
    <script src="{% static 'main/js/datatable.js' %}"></script>
    <script src="{% static 'main/js/auto-complete.js' %}"></script>
</head>

<body>


    <div class="container">
        <div class="panel panel-default">
            <div class="panel-body">

                <nav class="navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                                  <span class="sr-only">Toggle navigation</span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>
                              </button>

                        <img src="/media/logo.png" style="padding: 0vh 0vh 0vh 1vh;" class="navbar-brand" id="icon">
                        <a class="navbar-brand" style="color: red;" href="/"><strong>VLUTE MACREG</strong></a>

                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        {% if user.is_authenticated %}
                        <ul class="nav navbar-nav">
                            <li><a href="/guest/connections"><strong>Danh sách kết nối</strong></a></li>
                            <li><a href="/guest/list"><strong>Danh sách thiết bị</strong></a></li>
                            <li><a href="/student/list"><strong>Danh sách sinh viên</strong></a></li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong>Xin chào {{request.user | upper}}</strong><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/accounts/logout/">Thoát</a></li>
                                </ul>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
                {% block content %} {% endblock content %}
            </div>
            <div class="panel-footer" style="text-align: center;">
                <p>Bản quyền thuộc về <strong>Nhựt Thiên</strong> | © 2021</p>
                <a href="http://vlute.edu.vn/" style="text-decoration: none;">
                    <p>TRƯỜNG ĐẠI HỌC SƯ PHẠM KỸ THUẬT VĨNH LONG</p>
                </a>
                <p>Địa chỉ: 73 Nguyễn Huệ, phường 2, thành phố Vĩnh Long, tỉnh Vĩnh Long</p>
                <p>Email: spkt@vlute.edu.vn</p>
            </div>
        </div>
    </div>
</body>
{% block script %} {% endblock script %}

</html>

main/templates/guest_black_list.html
{% extends "base.html"%}{% block title %} VLUTE | BlACK LIST {% endblock title %} {% block content %}
<div class="col-xs-12 col-sm-9 col-md-6 col-lg-6 col-md-offset-3">
    <div class="form-group">
        <h4 style="color: red;"><strong><center>⚠️Thiết bị này đã bị chặn kết nối⚠️</center></strong></h4>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr style="background-color: chocolate; color: white">
                    <th style="text-align: center;">Thông tin</th>
                    <th style="text-align: center;">Chi tiết</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>Địa chỉ MAC thiết bị kết nối</strong></td>
                    <td style="text-align: center;"><strong>{{client | upper }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Địa chỉ MAC của AP</strong></td>
                    <td style="text-align: center;"><strong>{{ap | upper }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Tên WIFI</strong></td>
                    <td style="text-align: center;"><strong>{{ssid | upper }}</strong></td>
                </tr>
            </tbody>
        </table>

    </div>
    <div>
        <center>Xin vui lòng liên hệ với quản trị viên. Cám ơn!</center>
    </div>
</div>
{% endblock content %}

main/templates/guest_client_connections.html
{% extends "base.html" %} {% block title %} VLUTE | DETAIL {% endblock title %} {% block content %}
<div class="form-group">
    <h3><strong><center>Danh sách thiết bị kết nối WIFI</center></strong></h3>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Tên WIFI</th>
                <th>Địa chỉ MAC thiết bị</th>
                <th>Địa chỉ MAC AP</th>
                <th>Băng thông download</th>
                <th>Băng thông upload</th>
                <th>Tín hiệu WIFI</th>
                <th>Tình trạng xác thực</th>
                <th>Quản lý</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
            <tr>
                <td>{{client.essid | upper}}</td>
                <td>{{client.mac | upper }}</td>
                <td>{{client.ap_mac | upper }}</td>
                <td>{{client.rx_rate}} (Bytes)</td>
                <td>{{client.tx_rate}} (Bytes)</td>
                <td>{{client.signal}} dBm</td>
                {% if client.authorized == True %}
                <td>Đã xác thực</td>
                {% else %}
                <td>Chưa xác thực</td>
                {% endif %}
                <td id="kick-out">
                    <button type="button" id="{{client.mac}}" class="btn btn-danger">Disconnect</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %} {% block script %}
<script>
    $(document).ready(function() {
        $('td').css('text-align', 'center')
        $('th').css('text-align', 'center')
        $('th').css('background-color', 'chocolate')
        $('th').css('color', 'white')
        $('button').click(function(e) {
            let client_mac = e.target.id
            let kick_out_confirm = confirm('Xác nhận kick-out thiết bị này')
            if (kick_out_confirm == true) {
                $.ajax({
                    url: '/api/kick_out_client',
                    dataType: 'json',
                    data: {
                        'client_mac': client_mac
                    },
                    success: function(data) {
                        if (data.status == 'OK') {
                            alert(data.msg)
                            location.reload();
                        } else {
                            alert(data.msg)
                        }
                    }
                })
            }
        })
    })
</script>
{% endblock script %}

main/templates/guest_client_detail.html
{% extends "base.html" %} {% block title %} VLUTE | DETAIL {% endblock title %} {% block content %}
<div class="form-group">
    <h3><strong><center>Danh sách thiết bị kết nối WIFI</center></strong></h3>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-hover" id="table">
        <thead>
            <tr>
                <th>Tên WIFI</th>
                <th>Địa chỉ MAC thiết bị</th>
                <th>Địa chỉ MAC AP</th>
                <th>Băng thông download</th>
                <th>Băng thông upload</th>
                <th>Tín hiệu WIFI</th>
                <th>Tình trạng xác thực</th>
                <th>Quản lý</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
            <tr>
                <td>{{client.essid | upper}}</td>
                <td>{{client.mac | upper }}</td>
                <td>{{client.ap_mac | upper }}</td>
                <td>{{client.rx_bytes}} (Bytes)</td>
                <td>{{client.tx_bytes}} (Bytes)</td>
                <td>{{client.signal}}dBm</td>
                {% if client.authorized == True %}
                <td>Đã xác thực</td>
                {% else %}
                <td>Chưa xác thực</td>
                {% endif %}
                <td id="kick-out">
                    <button type="button" id="{{client.mac}}" class="btn btn-danger btn">Disconnect</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %} {% block script %}
<script>
    $(document).ready(function() {
        $('#table').DataTable({
            responsive: true
        })
        $('td').css('text-align', 'center')
        $('th').css('text-align', 'center')
        $('th').css('background-color', 'chocolate')
        $('th').css('color', 'white')
        $('.btn').click(function(e) {
            let client_mac = e.target.id
            let kick_out_confirm = confirm('Xác nhận kick-out thiết bị này')
            if (kick_out_confirm == true) {
                $.ajax({
                    url: '/api/kick_out_client',
                    dataType: 'json',
                    data: {
                        'client_mac': client_mac
                    },
                    success: function(data) {
                        if (data.status == 'OK') {
                            alert(data.msg)
                            location.reload();
                        } else {
                            alert(data.msg)
                        }
                    }
                })
            }
        })
    })
</script>
{% endblock script %}

main/templates/guest_client_list.html
{% extends "base.html" %} {% block title %} VLUTE | LIST {% endblock title %} {% block content %}
<div class="form-group">
    <h3><strong><center>Danh sách thiết bị đăng ký</center></strong></h3>
</div>
<div class="table-responsive">
    <table class="table table-hover table-bordered" id="table">
        <thead>
            <tr style="background-color: chocolate; color:white; text-align:center;">
                <th style="text-align: center;">MAC thiết bị</th>
                <th style="text-align: center;">Email đăng ký</th>
                <th style="text-align: center;">Họ và tên</th>
                <th style="text-align: center;">Thiết bị</th>
                <th style="text-align: center;">Upload</th>
                <th style="text-align: center;">Download</th>
                <th style="text-align: center;">Sử dụng</th>
                <th style="text-align: center;">Trạng thái</th>
                <th style="text-align: center;">Quản lý</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
            <tr>
                <td style="text-align: center;"><a style="text-decoration: none;" href="/guest/list/{{client.id}}"><button><strong>{{client.device_mac_address | upper}}</strong></button></a></td>
                <td style="text-align: center;">{{client.email}}</td>
                <td style="text-align: center;">{{client.name}}</td>
                <td style="text-align: center;">{{client.device_model}}</td>
                <td style="text-align: center;">{{client.bw_upload}} Kbps</td>
                <td style="text-align: center;">{{client.bw_download}} Kbps</td>
                <td style="text-align: center;">{{client.time_used}} Phút</td>
                <td style="text-align: center;">{{client.status}}</td>
                <td style="text-align: center;"><button type="button" id="{{client.device_mac_address}}" class="btn btn-danger btn">Delete</button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %} {% block script %}
<script>
    $(document).ready(function() {
        $('#table').DataTable({
            responsive: true
        })
        $('.btn').click(function(e) {
            let client = e.target.id
            let kick_out_confirm = confirm('Xác nhận xóa thiết bị này')
            if (kick_out_confirm == true) {
                $.ajax({
                    url: '/api/request_delete_client',
                    dataType: 'json',
                    data: {
                        'client': client
                    },
                    success: function(data) {
                        if (data.status == 'OK') {
                            alert(data.msg)
                            location.reload();
                        } else {
                            alert(data.msg)
                        }
                    }
                })
            }
        })
    })
</script>
{% endblock script %}

main/templates/guest_client_register.html
{% extends "base.html"%} {% block title %} VLUTE | REGISTER {% endblock title %} {% block content %} {% load crispy_forms_tags %} {% load static %}
<div id="client-default-block">
    <div class="form-group">
        <div class="text-center form-group" style="font-size:120%"><strong>HỆ THỐNG TRUY CẬP MẠNG KHÔNG DÂY VULTE</strong></div>
        <div class="text-center form-group">Địa chỉ MAC: <strong>{{client | upper}}</strong></div>
        <div class="text-center form-group">Mạng WiFi đang kết nối: <strong>{{ssid | upper}}</strong></div>
        <div class="text-center form-group"><strong>Thiết bị này chưa được đăng ký với hệ thống.</strong></div>
        <div class="text-center form-group">Nếu bạn là cán bộ, giảng viên hay sinh viên của trường thì ấn nút <strong>ĐĂNG KÝ</strong> để sử dụng hệ thống WiFi</div>
    </div>
    <div class="form-group text-center">
        <button type="button" class="btn btn-lg btn-success" id="register-button">Đăng ký</button>
    </div>
</div>
<div id="client-register-block">
    <div class="col-xs-12 col-sm-9 col-md-6 col-lg-4 col-md-offset-4">
        <div class="form-group text-center" style="font-size:150%"><strong>Đăng ký truy cập WIFI</strong></div>
        <form method="POST" id="form">
            {% csrf_token %} {{form | crispy}}
            <button type="submit" id="btn" class="btn btn-large btn-block btn-success form-group">Đăng ký</button>
        </form>
    </div>
</div>
{% endblock content %} {% block script %}
<script>
    $(document).ready(function() {
        $(function() {
            $('#client-register-block').hide()
            $('strong').css('color', 'red')
            $('#id_device_mac_address').val('{{client}}')
            $('#id_device_mac_address').prop('readonly', true)
            $('#id_ap_mac_address').val('{{ap}}')
            $('#id_ap_mac_address').prop('readonly', true)
        })
        $(function() {
            $.ajax({
                url: '/api/request_list_student_auto_complete',
                dataType: 'json',
                success: function(data) {
                    $('#id_email').autocomplete({
                        source: data.student_email_list
                    })
                }
            })
        })
        $(function() {
            $('#id_name').on('click', function() {
                let student_email = $('#id_email').val()
                $.ajax({
                    url: '/api/request_check_student_information',
                    dataType: 'json',
                    data: {
                        'student_email': student_email
                    },
                    success: function(data) {
                        $('#id_name').val(data.student_name)
                        $('#id_classmate').val(data.student_classmate)
                    }
                })
            })
        })
        $(function() {
            $('#register-button').click(function() {
                $('#client-default-block').hide()
                $('#client-register-block').fadeIn(500)
            })
            $('#form').on('submit', function() {
                $('#btn').prop('disabled', true)
                $('#btn').text('Đang xử lý, vui lòng chờ!!!')
            });
        })
    })
</script>
{% endblock script %}

main/templates/guest_default_portal.html
{% extends "base.html"%} {% block title %} VLUTE | REGISTER {% endblock title %} {% block content %} {% load crispy_forms_tags %} {% load static %}
<div class="col-xs-12 col-sm-9 col-md-6 col-lg-4 col-md-offset-4">
    <div class="form-group">
        <h3><strong><center>Đăng ký truy cập WIFI</center></strong></h3>
    </div>
    <form method="POST" id="form">
        {% csrf_token %} {{form | crispy}}
        <div class="form-group">
            <button type="submit" id="btn" class="btn btn-large btn-block btn-success">Đăng ký</button>
        </div>
    </form>
</div>
{% endblock content %} {% block script %}
<script>
    $(document).ready(function() {
        $('strong').css('color', 'red')
        $('#id_device_mac_address').val('{{client}}')
        $('#id_device_mac_address').prop('readonly', true)
        $('#id_ap_mac_address').val('{{ap}}')
        $('#id_ap_mac_address').prop('readonly', true)
        $('#form').on('submit', function() {
            $('#btn').prop('disabled', true)
            $('#btn').text('Đang xử lý, vui lòng chờ!!!')
        })
    })
</script>
{% endblock script %}

main/templates/home.html
{% extends "base.html" %} {% block title %} VLUTE | HOME {% endblock title %} {% block content %}
<div class="responsive">
    <h3 style="font-family:'Lucida Sans'; color: red"><strong><center>WIFI MANAGEMENT SYSTEM</center></strong></h3>
</div>
<div class="form-group">
    <img src="/media/anh-bia.jpg" class="img-responsive" alt="Image">
</div>
{% endblock content %}

main/templates/update_user_information.html
{% extends "base.html"%} {% block title %} VLUTE | UPDATE {% endblock title %} {% block content %} {% load crispy_forms_tags %} {% load static %}
<div class="col-xs-12 col-sm-9 col-md-6 col-lg-4 col-md-offset-4">
    <div class="form-group">
        <h3><strong><center>Cập nhật thông tin</center></strong></h3>
    </div>
    <form method="POST" id="form">
        {% csrf_token %} {{form | crispy}}
        <div class="form-group">
            <button type="submit" id="btn" class="btn btn-success">Cập nhật</button>
            <a href="/guest/list"><button type="button" class="btn btn-warning">Quay lại</button></a>
        </div>
    </form>
</div>
{% endblock content %} {% block script %}
<script>
    $(document).ready(function() {
        $('#id_device_mac_address').prop('readonly', true)
    })
</script>
{% endblock script %}